### ISSUE TITLE
Page Disorder

### ISSUE THREAD

**Issue by cuscada** [htdvisser/hugo-base16-theme#12]
Hi dev.
Thank you for submitting this awesome project. Can I ask a support from you directly?
I did all your manuals in your readme.md which are put `pymentsuseclasses = true` in the config.toml and did `pip install Pygments`

However when I did try both `Hugo server` and `Hugo`, the result are the same. Page disorder.
![page-disorder](https://cloud.githubusercontent.com/assets/18105757/19559486/4fab97b2-96fa-11e6-87b5-6efa46c93c24.png)

I can't make it to appear like yours [https://htdvisser.github.io/hugo-base16-theme/]

Can you please tell what should I do?
Thank you in advanced.

**Comment by htdvisser** [comment]
I do the following:

```
hugo new site testsite
cd testsite
git clone https://github.com/htdvisser/hugo-base16-theme.git themes/base16
hugo server --theme base16
```

When I then go to http://localhost:1313 I see:

![screen shot 2016-10-20 at 14 59 08](https://cloud.githubusercontent.com/assets/181308/19560715/c8374a48-96d5-11e6-9632-6dd9c10deb59.png)

Not sure how I can help you. Please try the commands above. I hope it works.

**Comment by cuscada** [comment]
Thank you for the immediate reply.
It works, if the baseURL is at the main directory.
Can you try if making the baseURL to be a subdirectory, such as `localhost:1313/myblog` , then it will turn out to be page disorder. Is it some bug? Thanks:)
