### ISSUE TITLE
Images missing max-width property

### ISSUE THREAD

**Issue by paskal** [htdvisser/hugo-base16-theme#15]
Hello!

The very same issue as the one I've reported https://github.com/dim0627/hugo_theme_beg/issues/19 to other project:
![image](https://user-images.githubusercontent.com/712534/37653438-f102e11a-2c4f-11e8-9e56-a98145d086d0.png)

Source code:

    ![Shinken simple distributed architecture](https://shinken.readthedocs.io/en/latest/_images/shinken-architecture.png)

**Comment by htdvisser** [comment]
Hi @paskal, thanks for reporting. Do you have the time to submit a pull request with a fix for this? I'm not actively working on this project right now, so it may take some time before I can take a look at it.

I'm pretty sure most of the CSS is already there, except that it applies to the [`figure` shortcode](https://gohugo.io/content-management/shortcodes/#figure)

**Comment by paskal** [comment]
Sorry, I won't be able to prepare a pull request. The thing is for someone `img` is enough (https://github.com/dim0627/hugo_theme_beg/commit/7718359506a2447ef0489dcd6bd7360f21eb93cb), for someone it's `.single .meta img` (https://github.com/marcanuy/hugotube/commit/84b3be1ef1b1521911890cc1814e583a7ab257e5) - you're the best person to decide what should be done here because you have all the context.
