### ISSUE TITLE
Add support for Pagination

### ISSUE THREAD

**Issue by htdvisser** [htdvisser/hugo-base16-theme#2]
See http://gohugo.io/extras/pagination/

**Comment by ghost** [comment]
Is this coming anytime soon?

**Comment by htdvisser** [comment]
I'm not actively working on this project right now, so it may take some time before I can take a look at it. Would you have time to look at this and submit a pull request?

**Comment by ghost** [comment]
Unfortunately you are talking to dumbnuts here but I know a bit about HTMl, CSS and JS. I will look at the documentation and try to implement one :)

**Comment by htdvisser** [comment]
Closed by #18.
