### ISSUE TITLE
Posts are not showing

### ISSUE THREAD

**Issue by michaelsync** [htdvisser/hugo-base16-theme#23]
The posts are not showing after installing the hugo . I have followed the hugo quickstart to create the posts and changed the theme to use base16. I can see the theme, categories, tags but not posts. 

hugo version: Hugo Static Site Generator v0.55.6-A5D4C82D windows/amd64 BuildDate: 2019-05-18T07:57:00Z

![image](https://user-images.githubusercontent.com/192911/61605818-93fff400-ac8a-11e9-8dc9-29c16fb8746e.png)

**Comment by michaelsync** [comment]
Solved. 

It should be post (instead of posts).. But in quick start, it's using post https://gohugo.io/getting-started/quick-start/

**Comment by guanbear** [comment]
same problem
