### ISSUE TITLE
Content not showing up

### ISSUE THREAD

**Issue by aaryanporwal** [htdvisser/hugo-base16-theme#28]
The [official hugo docs](https://gohugo.io/getting-started/quick-start/#step-4-add-some-content) recommend using `content/posts` for adding content files, but this theme searches only for `content/post` (difference of a single character s) which can make beginner's life hell.
Spent hours trying to find this bug, which made my posts not show up.

Please add support for directory name `posts` as well

**Comment by htdvisser** [comment]
Thanks for reporting this. It should be fixed in 507fbbfb08f61873d5336bcc624846f88c4c8b72.
